# Generated by Django 5.0.6 on 2024-06-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etnia', models.CharField(choices=[('indigena', 'Indígena'), ('afrocolombiano', 'Afrocolombiano'), ('raizal', 'Raizal'), ('rom', 'Rom')], max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
        ),
    ]
