# Generated by Django 5.0.6 on 2024-06-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('etnia', models.CharField(choices=[('ninguna', 'Ninguna'), ('indigena', 'Indígena'), ('afrocolombiano', 'Afrocolombiano'), ('raizal', 'Raizal'), ('rom', 'Rom')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('grupo_antecedente', models.CharField(choices=[('personal', 'Personal'), ('familiar', 'Familiar')], max_length=50)),
                ('tipo_antecedente', models.CharField(choices=[('quirurgico', 'Quirúrgico'), ('alergico', 'Alergico'), ('traumatico', 'Traumático'), ('toxicologico', 'Toxicológico')], max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia.paciente', to_field='identificacion')),
            ],
        ),
    ]
