# Generated by Django 5.0.6 on 2024-06-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient',
            new_name='Paciente',
        ),
    ]
