# Generated by Django 5.0.6 on 2024-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_rename_patient_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('indigena', 'Indígena'), ('afrocolombiano', 'Afrocolombiano'), ('raizal', 'Raizal'), ('rom', 'Rom')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1),
        ),
    ]
