# Generated by Django 5.0.6 on 2024-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_paciente_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='justificacion_modificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Justificación de modificación'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('', 'Seleccione un género'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
