# Generated by Django 5.0.6 on 2024-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_historiaclinica_justificacion_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='justificacion_modificacion',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='anotacion',
            field=models.TextField(blank=True, null=True, verbose_name='Anotación'),
        ),
    ]
